In [10]:
import numpy as np
arr=np.random.randint(0,20,20)

print("Array",arr)
print("Mean",np.mean(arr))
print("Median",np.median(arr))
print("Standard dev",np.std(arr))

reshape_arr=np.reshape(arr,(4,5))
print(reshape_arr)

Array [12 12 11  0  4 19  4 19 17 19  3  9  8  9  6 19  8  0 19 14]
Mean 10.6
Median 10.0
Standard dev 6.398437309218556
[[12 12 11  0  4]
 [19  4 19 17 19]
 [ 3  9  8  9  6]
 [19  8  0 19 14]]
